# Client Application 
client_id = "" # required, provided by IdP
redirect_uri = "http://localhost:5000/callback" # required, set by Developer when requesting App in IdP

# OAuth2 Authorization code params
response_type = "code" # required for Authorization Code OAuth2 flow
authorization_base_url = 'https://example-idp.com/oauth2/authorize' # required, provided by the OIDC spec of the IdP
token_url = 'https://example-idp.com/oauth2/token' # required, provided by the OIDC spec of the IdP
scope = ['A', 'B', 'C'] # optional

# Protected resource
protected_uri= "http://httpbin.org/headers" # required, this endpoint must accept access tokens which are generated by the IdP 
headers = {"Host": "httpbin.org"} # optional, headers which will be sent to the endpoint